#!/usr/bin/env python3
"""Regenerate src/data/heroes.ts and src/data/items.ts from the raw Deadlock
API exports in data/raw/. Re-run this whenever fresher JSON exports are
dropped in, instead of hand-editing the generated .ts files.

Usage: python3 scripts/generate_data.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw"
OUT = ROOT / "src" / "data"

# Maps our simplified StatKey model (src/types.ts) onto the raw API's item
# property keys. The API exposes dozens of situational/conditional
# properties (on-ambush, on-proc, while-sliding, etc.) that don't fit a
# simple additive stat model — we only pull the unconditional passive
# stats that make up the bulk of an item's value. Where multiple raw keys
# map to one StatKey (e.g. TechPower/SpiritPower), they never co-occur on
# the same item in practice, so summing is safe.
STAT_PROPERTY_MAP = {
    "maxHealth": ["BonusHealth"],
    "bulletDamage": ["BaseAttackDamagePercent"],
    "fireRate": ["BonusFireRate"],
    "bulletResist": ["BulletResist"],
    "spiritResist": ["TechResist"],
    "spiritPower": ["TechPower", "SpiritPower"],
    "cooldownReduction": ["CooldownReduction"],
    "healthRegen": ["OutOfCombatHealthRegen", "BonusHealthRegen"],
    "moveSpeed": ["BonusMoveSpeed", "BonusSprintSpeed"],
    "lifesteal": ["AbilityLifestealPercentHero", "BulletLifestealPercent"],
}

STAT_LABELS = {
    "maxHealth": "Max Health",
    "bulletDamage": "Bullet Damage",
    "fireRate": "Fire Rate",
    "bulletResist": "Bullet Resist",
    "spiritResist": "Spirit Resist",
    "spiritPower": "Spirit Power",
    "cooldownReduction": "Cooldown Reduction",
    "healthRegen": "Health Regen",
    "moveSpeed": "Move Speed",
    "lifesteal": "Lifesteal",
}

STAT_UNITS = {
    "bulletDamage": "%",
    "fireRate": "%",
    "bulletResist": "%",
    "spiritResist": "%",
    "cooldownReduction": "%",
    "lifesteal": "%",
    "healthRegen": "/s",
}

# hero_type -> our HeroArchetype, plus a starting stat-priority preset.
ARCHETYPE_BY_HERO_TYPE = {
    "marksman": "bullet",
    "mystic": "spirit",
    "brawler": "vitality",
    "assassin": "hybrid",
}

DEFAULT_WEIGHTS_BY_ARCHETYPE = {
    "bullet": {"bulletDamage": 0.9, "fireRate": 0.6, "maxHealth": 0.3, "bulletResist": 0.3, "lifesteal": 0.3},
    "spirit": {"spiritPower": 0.9, "cooldownReduction": 0.6, "maxHealth": 0.3, "spiritResist": 0.3},
    "vitality": {"maxHealth": 0.8, "bulletResist": 0.5, "lifesteal": 0.5, "bulletDamage": 0.3},
    "hybrid": {"bulletDamage": 0.5, "spiritPower": 0.5, "maxHealth": 0.4, "cooldownReduction": 0.3},
}


def to_num(value):
    if value is None:
        return 0
    try:
        return float(value)
    except (TypeError, ValueError):
        match = re.findall(r"-?\d+\.?\d*", str(value))
        return float(match[0]) if match else 0


def clean_number(value):
    rounded = round(value, 2)
    return int(rounded) if rounded == int(rounded) else rounded


def js_string(value: str) -> str:
    return json.dumps(value)


def generate_items():
    with open(RAW / "deadlock_items.json") as f:
        raw_items = json.load(f)

    shop_items = [
        it for it in raw_items
        if it.get("item_slot_type") in ("weapon", "vitality", "spirit") and it.get("shopable")
    ]

    entries = []
    for it in shop_items:
        props = it.get("properties", {})
        stats = {}
        for stat_key, prop_keys in STAT_PROPERTY_MAP.items():
            total = sum(to_num(props.get(pk, {}).get("value")) for pk in prop_keys)
            if total:
                stats[stat_key] = clean_number(total)

        if not stats:
            continue  # active/utility items whose value isn't a passive stat we model

        description = ", ".join(
            f"+{v}{STAT_UNITS.get(k, '')} {STAT_LABELS[k]}" for k, v in stats.items()
        )

        entries.append({
            "id": it["class_name"],
            "name": it["name"],
            "category": it["item_slot_type"],
            "tier": it["item_tier"],
            "cost": it["cost"],
            "stats": stats,
            "description": description,
        })

    entries.sort(key=lambda e: (e["category"], e["tier"], e["cost"]))

    lines = [
        "import type { Item } from '../types'",
        "",
        "// Generated by scripts/generate_data.py from data/raw/deadlock_items.json",
        "// (official Deadlock API export). Only unconditional passive stats are",
        "// mapped — see STAT_PROPERTY_MAP in that script for exactly which raw",
        "// properties feed each StatKey. Re-run the script after refreshing the",
        "// raw export instead of hand-editing this file.",
        "export const ITEMS: Item[] = [",
    ]
    for e in entries:
        stats_js = ", ".join(f"{k}: {v}" for k, v in e["stats"].items())
        lines.append("  {")
        lines.append(f"    id: {js_string(e['id'])},")
        lines.append(f"    name: {js_string(e['name'])},")
        lines.append(f"    category: {js_string(e['category'])},")
        lines.append(f"    tier: {e['tier']},")
        lines.append(f"    cost: {e['cost']},")
        lines.append(f"    stats: {{ {stats_js} }},")
        lines.append(f"    description: {js_string(e['description'])},")
        lines.append("  },")
    lines.append("]")

    (OUT / "items.ts").write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} items to src/data/items.ts (dropped {len(shop_items) - len(entries)} with no mapped passive stat)")


def generate_heroes():
    with open(RAW / "deadlock_heroes.json") as f:
        raw_heroes = json.load(f)

    playable = [h for h in raw_heroes if h.get("player_selectable") and not h.get("disabled")]

    entries = []
    for h in playable:
        hero_type = h.get("hero_type")
        archetype = ARCHETYPE_BY_HERO_TYPE.get(hero_type, "hybrid")
        starting = h.get("starting_stats", {})
        max_health = starting.get("max_health", {}).get("value", 600)
        move_speed = starting.get("max_move_speed", {}).get("value", 6)
        role = (h.get("description") or {}).get("role") or ""
        hero_id = re.sub(r"^hero_", "", h["class_name"])

        entries.append({
            "id": hero_id,
            "name": h["name"],
            "role": role,
            "archetype": archetype,
            "maxHealth": clean_number(max_health),
            "moveSpeed": clean_number(move_speed),
            "defaultWeights": DEFAULT_WEIGHTS_BY_ARCHETYPE[archetype],
        })

    entries.sort(key=lambda e: e["name"])

    lines = [
        "import type { Hero } from '../types'",
        "",
        "// Generated by scripts/generate_data.py from data/raw/deadlock_heroes.json",
        "// (official Deadlock API export). Archetype is derived from the API's",
        "// hero_type field (marksman/mystic/brawler/assassin); defaultWeights are",
        "// a preset per archetype, not individually hand-tuned per hero. Re-run",
        "// the script after refreshing the raw export instead of hand-editing.",
        "export const HEROES: Hero[] = [",
    ]
    for e in entries:
        weights_js = ", ".join(f"{k}: {v}" for k, v in e["defaultWeights"].items())
        lines.append("  {")
        lines.append(f"    id: {js_string(e['id'])},")
        lines.append(f"    name: {js_string(e['name'])},")
        lines.append(f"    role: {js_string(e['role'])},")
        lines.append(f"    archetype: {js_string(e['archetype'])},")
        lines.append(f"    baseStats: {{ maxHealth: {e['maxHealth']}, moveSpeed: {e['moveSpeed']} }},")
        lines.append(f"    defaultWeights: {{ {weights_js} }},")
        lines.append("  },")
    lines.append("]")

    (OUT / "heroes.ts").write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} heroes to src/data/heroes.ts")


if __name__ == "__main__":
    generate_items()
    generate_heroes()
