#!/usr/bin/env python3
"""Regenerate src/data/heroes.ts and src/data/items.ts from the raw Deadlock
API exports in data/raw/. Re-run this whenever fresher JSON exports are
dropped in, instead of hand-editing the generated .ts files.

Usage: python3 scripts/generate_data.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw"
OUT = ROOT / "src" / "data"

# Maps our simplified StatKey model (src/types.ts) onto the raw API's item
# property keys. The API exposes dozens of situational/conditional
# properties (on-ambush, on-proc, while-sliding, etc.) that don't fit a
# simple additive stat model — we only pull the unconditional passive
# stats that make up the bulk of an item's value. Where multiple raw keys
# map to one StatKey (e.g. TechPower/SpiritPower), they never co-occur on
# the same item in practice, so summing is safe.
STAT_PROPERTY_MAP = {
    "maxHealth": ["BonusHealth"],
    "bulletDamage": ["BaseAttackDamagePercent"],
    "fireRate": ["BonusFireRate"],
    "bulletResist": ["BulletResist"],
    "spiritResist": ["TechResist"],
    "spiritPower": ["TechPower", "SpiritPower"],
    "cooldownReduction": ["CooldownReduction"],
    "healthRegen": ["OutOfCombatHealthRegen", "BonusHealthRegen"],
    "moveSpeed": ["BonusMoveSpeed", "BonusSprintSpeed"],
    "lifesteal": ["AbilityLifestealPercentHero", "BulletLifestealPercent"],
}

STAT_LABELS = {
    "maxHealth": "Max Health",
    "bulletDamage": "Bullet Damage",
    "fireRate": "Fire Rate",
    "bulletResist": "Bullet Resist",
    "spiritResist": "Spirit Resist",
    "spiritPower": "Spirit Power",
    "cooldownReduction": "Cooldown Reduction",
    "healthRegen": "Health Regen",
    "moveSpeed": "Move Speed",
    "lifesteal": "Lifesteal",
}

STAT_UNITS = {
    "bulletDamage": "%",
    "fireRate": "%",
    "bulletResist": "%",
    "spiritResist": "%",
    "cooldownReduction": "%",
    "lifesteal": "%",
    "healthRegen": "/s",
}

# hero_type -> our HeroArchetype, plus a starting stat-priority preset.
ARCHETYPE_BY_HERO_TYPE = {
    "marksman": "bullet",
    "mystic": "spirit",
    "brawler": "vitality",
    "assassin": "hybrid",
}

DEFAULT_WEIGHTS_BY_ARCHETYPE = {
    "bullet": {"bulletDamage": 0.9, "fireRate": 0.6, "maxHealth": 0.3, "bulletResist": 0.3, "lifesteal": 0.3},
    "spirit": {"spiritPower": 0.9, "cooldownReduction": 0.6, "maxHealth": 0.3, "spiritResist": 0.3},
    "vitality": {"maxHealth": 0.8, "bulletResist": 0.5, "lifesteal": 0.5, "bulletDamage": 0.3},
    "hybrid": {"bulletDamage": 0.5, "spiritPower": 0.5, "maxHealth": 0.4, "cooldownReduction": 0.3},
}


def to_num(value):
    if value is None:
        return 0
    try:
        return float(value)
    except (TypeError, ValueError):
        match = re.findall(r"-?\d+\.?\d*", str(value))
        return float(match[0]) if match else 0


def clean_number(value):
    rounded = round(value, 2)
    return int(rounded) if rounded == int(rounded) else rounded


def js_string(value: str) -> str:
    return json.dumps(value)


def generate_items():
    with open(RAW / "deadlock_items.json") as f:
        raw_items = json.load(f)

    shop_items = [
        it for it in raw_items
        if it.get("item_slot_type") in ("weapon", "vitality", "spirit") and it.get("shopable")
    ]

    entries = []
    for it in shop_items:
        props = it.get("properties", {})
        stats = {}
        for stat_key, prop_keys in STAT_PROPERTY_MAP.items():
            total = sum(to_num(props.get(pk, {}).get("value")) for pk in prop_keys)
            if total:
                stats[stat_key] = clean_number(total)

        if not stats:
            continue  # active/utility items whose value isn't a passive stat we model

        description = ", ".join(
            f"+{v}{STAT_UNITS.get(k, '')} {STAT_LABELS[k]}" for k, v in stats.items()
        )

        entries.append({
            "id": it["class_name"],
            "name": it["name"],
            "category": it["item_slot_type"],
            "tier": it["item_tier"],
            "cost": it["cost"],
            "stats": stats,
            "description": description,
            # WebP shop icon (200x200, ~20KB) served from the official CDN.
            # Filenames follow internal codenames rather than class_name, so
            # these URLs have to come from the export, not be constructed.
            "image": it.get("shop_image_webp") or it.get("shop_image") or "",
        })

    entries.sort(key=lambda e: (e["category"], e["tier"], e["cost"]))

    lines = [
        "import type { Item } from '../types'",
        "",
        "// Generated by scripts/generate_data.py from data/raw/deadlock_items.json",
        "// (official Deadlock API export). Only unconditional passive stats are",
        "// mapped — see STAT_PROPERTY_MAP in that script for exactly which raw",
        "// properties feed each StatKey. Re-run the script after refreshing the",
        "// raw export instead of hand-editing this file.",
        "export const ITEMS: Item[] = [",
    ]
    for e in entries:
        stats_js = ", ".join(f"{k}: {v}" for k, v in e["stats"].items())
        lines.append("  {")
        lines.append(f"    id: {js_string(e['id'])},")
        lines.append(f"    name: {js_string(e['name'])},")
        lines.append(f"    category: {js_string(e['category'])},")
        lines.append(f"    tier: {e['tier']},")
        lines.append(f"    cost: {e['cost']},")
        lines.append(f"    stats: {{ {stats_js} }},")
        lines.append(f"    description: {js_string(e['description'])},")
        lines.append(f"    image: {js_string(e['image'])},")
        lines.append("  },")
    lines.append("]")

    (OUT / "items.ts").write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} items to src/data/items.ts (dropped {len(shop_items) - len(entries)} with no mapped passive stat)")


def generate_heroes():
    with open(RAW / "deadlock_heroes.json") as f:
        raw_heroes = json.load(f)

    playable = [h for h in raw_heroes if h.get("player_selectable") and not h.get("disabled")]

    entries = []
    for h in playable:
        hero_type = h.get("hero_type")
        archetype = ARCHETYPE_BY_HERO_TYPE.get(hero_type, "hybrid")
        starting = h.get("starting_stats", {})
        max_health = starting.get("max_health", {}).get("value", 600)
        move_speed = starting.get("max_move_speed", {}).get("value", 6)
        health_regen = starting.get("base_health_regen", {}).get("value", 0)
        role = (h.get("description") or {}).get("role") or ""
        hero_id = re.sub(r"^hero_", "", h["class_name"])
        images = h.get("images") or {}
        # Levels 2..36 each grant one "standard upgrade", so a level-L hero
        # has had these applied (L - 1) times. The per-level amounts vary a
        # lot by hero (health 27-65), so they can't be a shared constant.
        per_level = h.get("standard_level_up_upgrades") or {}

        entries.append({
            "id": hero_id,
            "name": h["name"],
            "role": role,
            "archetype": archetype,
            "maxHealth": clean_number(max_health),
            "moveSpeed": clean_number(move_speed),
            "healthRegen": clean_number(health_regen),
            "perLevelHealth": clean_number(per_level.get("MODIFIER_VALUE_BASE_HEALTH_FROM_LEVEL", 0)),
            "perLevelSpiritPower": clean_number(per_level.get("MODIFIER_VALUE_TECH_POWER", 0)),
            "perLevelBulletDamage": clean_number(
                per_level.get("MODIFIER_VALUE_BASE_BULLET_DAMAGE_FROM_LEVEL", 0)),
            "defaultWeights": DEFAULT_WEIGHTS_BY_ARCHETYPE[archetype],
            # WebP portrait icon (128x128, ~12KB) from the official CDN.
            "image": images.get("icon_image_small_webp") or images.get("icon_image_small") or "",
        })

    entries.sort(key=lambda e: e["name"])

    lines = [
        "import type { Hero } from '../types'",
        "",
        "// Generated by scripts/generate_data.py from data/raw/deadlock_heroes.json",
        "// (official Deadlock API export). Archetype is derived from the API's",
        "// hero_type field (marksman/mystic/brawler/assassin); defaultWeights are",
        "// a preset per archetype, not individually hand-tuned per hero. Re-run",
        "// the script after refreshing the raw export instead of hand-editing.",
        "export const HEROES: Hero[] = [",
    ]
    for e in entries:
        weights_js = ", ".join(f"{k}: {v}" for k, v in e["defaultWeights"].items())
        lines.append("  {")
        lines.append(f"    id: {js_string(e['id'])},")
        lines.append(f"    name: {js_string(e['name'])},")
        lines.append(f"    role: {js_string(e['role'])},")
        lines.append(f"    archetype: {js_string(e['archetype'])},")
        lines.append(
            f"    baseStats: {{ maxHealth: {e['maxHealth']}, moveSpeed: {e['moveSpeed']}, "
            f"healthRegen: {e['healthRegen']} }},"
        )
        lines.append(
            f"    perLevel: {{ maxHealth: {e['perLevelHealth']}, "
            f"spiritPower: {e['perLevelSpiritPower']}, "
            f"bulletDamage: {e['perLevelBulletDamage']} }},"
        )
        lines.append(f"    defaultWeights: {{ {weights_js} }},")
        lines.append(f"    image: {js_string(e['image'])},")
        lines.append("  },")
    lines.append("]")

    (OUT / "heroes.ts").write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} heroes to src/data/heroes.ts")


def generate_investment():
    """Emit the soul-investment bonus table.

    Each category grants a cumulative bonus once its spend crosses a
    threshold — a step function over 11 tiers, not a single cutoff. Units
    differ: weapon and vitality are percentages, spirit is flat. The 4800
    tier is the milestone, by far the largest single jump in all three.
    """
    with open(RAW / "deadlock_investment.json") as f:
        raw = json.load(f)

    # Raw stat names -> the StatKey they affect in this app.
    STAT_TO_KEY = {
        "weapon_damage": "bulletDamage",
        "health": "maxHealth",
        "spirit_power": "spiritPower",
    }

    lines = [
        "import type { ItemCategory } from '../types'",
        "",
        "// Generated by scripts/generate_data.py from",
        "// data/raw/deadlock_investment.json. Cumulative values match the",
        "// cost_bonuses table in the hero export.",
        "//",
        "// The bonus is the cumulative value of the highest threshold whose",
        "// soul requirement the category's spend has reached — a step",
        "// function, never interpolated. Below 800 souls it is zero.",
        "export interface InvestmentTier {",
        "  souls: number",
        "  /** Increment gained at this tier. */",
        "  individual: number",
        "  /** Total bonus once this tier is reached. */",
        "  cumulative: number",
        "  milestone: boolean",
        "}",
        "",
        "export interface InvestmentCategory {",
        "  statKey: 'bulletDamage' | 'maxHealth' | 'spiritPower'",
        "  unit: 'percent' | 'flat'",
        "  label: string",
        "  tiers: InvestmentTier[]",
        "}",
        "",
        f"export const INVESTMENT_THRESHOLDS = {json.dumps(raw['thresholds'])}",
        "",
        "/** The starred tier: the largest single jump in every category. */",
        "export const MILESTONE_SOULS = 4800",
        "",
        "export const INVESTMENT: Record<ItemCategory, InvestmentCategory> = {",
    ]
    for category, spec in raw["categories"].items():
        lines.append(f"  {category}: {{")
        lines.append(f"    statKey: {js_string(STAT_TO_KEY[spec['stat']])},")
        lines.append(f"    unit: {js_string(spec['unit'])},")
        lines.append(f"    label: {js_string(spec['label'])},")
        lines.append("    tiers: [")
        for t in spec["tiers"]:
            lines.append(
                f"      {{ souls: {t['souls']}, individual: {t['individual']}, "
                f"cumulative: {t['cumulative']}, milestone: {str(t['milestone']).lower()} }},"
            )
        lines.append("    ],")
        lines.append("  },")
    lines.append("}")
    lines += [
        "",
        "/** Cumulative bonus for a category at a given spend. */",
        "export function investmentBonus(category: ItemCategory, souls: number): number {",
        "  const tiers = INVESTMENT[category].tiers",
        "  let bonus = 0",
        "  for (const tier of tiers) {",
        "    if (souls >= tier.souls) bonus = tier.cumulative",
        "  }",
        "  return bonus",
        "}",
        "",
        "/** The next tier a category has not yet reached, or null at the cap. */",
        "export function nextInvestmentTier(",
        "  category: ItemCategory,",
        "  souls: number,",
        "): InvestmentTier | null {",
        "  return INVESTMENT[category].tiers.find((tier) => souls < tier.souls) ?? null",
        "}",
    ]

    (OUT / "investmentBonuses.ts").write_text("\n".join(lines) + "\n")
    print(f"Wrote investment table ({len(raw['thresholds'])} tiers x {len(raw['categories'])} categories) to src/data/investmentBonuses.ts")


if __name__ == "__main__":
    generate_items()
    generate_heroes()
    generate_investment()
