import type { ItemCategory } from '../types'

// Generated by scripts/generate_data.py from
// data/raw/deadlock_investment.json. Cumulative values match the
// cost_bonuses table in the hero export.
//
// The bonus is the cumulative value of the highest threshold whose
// soul requirement the category's spend has reached — a step
// function, never interpolated. Below 800 souls it is zero.
export interface InvestmentTier {
  souls: number
  /** Increment gained at this tier. */
  individual: number
  /** Total bonus once this tier is reached. */
  cumulative: number
  milestone: boolean
}

export interface InvestmentCategory {
  statKey: 'bulletDamage' | 'maxHealth' | 'spiritPower'
  unit: 'percent' | 'flat'
  label: string
  tiers: InvestmentTier[]
}

export const INVESTMENT_THRESHOLDS = [800, 1600, 2400, 3200, 4800, 6400, 8000, 11200, 16000, 22400, 28800]

/** The starred tier: the largest single jump in every category. */
export const MILESTONE_SOULS = 4800

export const INVESTMENT: Record<ItemCategory, InvestmentCategory> = {
  weapon: {
    statKey: "bulletDamage",
    unit: "percent",
    label: "Weapon Damage (%)",
    tiers: [
      { souls: 800, individual: 9, cumulative: 9, milestone: false },
      { souls: 1600, individual: 3, cumulative: 12, milestone: false },
      { souls: 2400, individual: 3, cumulative: 15, milestone: false },
      { souls: 3200, individual: 3, cumulative: 18, milestone: false },
      { souls: 4800, individual: 28, cumulative: 46, milestone: true },
      { souls: 6400, individual: 8, cumulative: 54, milestone: false },
      { souls: 8000, individual: 8, cumulative: 62, milestone: false },
      { souls: 11200, individual: 12, cumulative: 74, milestone: false },
      { souls: 16000, individual: 12, cumulative: 86, milestone: false },
      { souls: 22400, individual: 14, cumulative: 100, milestone: false },
      { souls: 28800, individual: 15, cumulative: 115, milestone: false },
    ],
  },
  vitality: {
    statKey: "maxHealth",
    unit: "percent",
    label: "Health (%)",
    tiers: [
      { souls: 800, individual: 9, cumulative: 9, milestone: false },
      { souls: 1600, individual: 3, cumulative: 12, milestone: false },
      { souls: 2400, individual: 3, cumulative: 15, milestone: false },
      { souls: 3200, individual: 5, cumulative: 20, milestone: false },
      { souls: 4800, individual: 18, cumulative: 38, milestone: true },
      { souls: 6400, individual: 4, cumulative: 42, milestone: false },
      { souls: 8000, individual: 4, cumulative: 46, milestone: false },
      { souls: 11200, individual: 4, cumulative: 50, milestone: false },
      { souls: 16000, individual: 4, cumulative: 54, milestone: false },
      { souls: 22400, individual: 6, cumulative: 60, milestone: false },
      { souls: 28800, individual: 6, cumulative: 66, milestone: false },
    ],
  },
  spirit: {
    statKey: "spiritPower",
    unit: "flat",
    label: "Spirit Power",
    tiers: [
      { souls: 800, individual: 7, cumulative: 7, milestone: false },
      { souls: 1600, individual: 4, cumulative: 11, milestone: false },
      { souls: 2400, individual: 4, cumulative: 15, milestone: false },
      { souls: 3200, individual: 4, cumulative: 19, milestone: false },
      { souls: 4800, individual: 19, cumulative: 38, milestone: true },
      { souls: 6400, individual: 7, cumulative: 45, milestone: false },
      { souls: 8000, individual: 7, cumulative: 52, milestone: false },
      { souls: 11200, individual: 7, cumulative: 59, milestone: false },
      { souls: 16000, individual: 7, cumulative: 66, milestone: false },
      { souls: 22400, individual: 9, cumulative: 75, milestone: false },
      { souls: 28800, individual: 25, cumulative: 100, milestone: false },
    ],
  },
}

/** Cumulative bonus for a category at a given spend. */
export function investmentBonus(category: ItemCategory, souls: number): number {
  const tiers = INVESTMENT[category].tiers
  let bonus = 0
  for (const tier of tiers) {
    if (souls >= tier.souls) bonus = tier.cumulative
  }
  return bonus
}

/** The next tier a category has not yet reached, or null at the cap. */
export function nextInvestmentTier(
  category: ItemCategory,
  souls: number,
): InvestmentTier | null {
  return INVESTMENT[category].tiers.find((tier) => souls < tier.souls) ?? null
}
